hikoky/scrapers/urls/urls.py
import json
import os
import urllib.parse
import re

json_file_manga = 'hikoky/scrapers/urls/data/links-manga.json'
chapter_link_file = 'hikoky/scrapers/urls/data/chapter_links.json'
latest_chapters_file = 'hikoky/scrapers/urls/data/latest_chapters.json'
chapter_data = 'hikoky/scrapers/urls/data/chapter_data.json'

def read_json_file(file_path):
    if os.path.exists(file_path):
        with open(file_path, 'r') as f:
            return json.load(f)
    return {}

def write_json_file(file_path, data):
    with open(file_path, 'w') as f:
        json.dump(data, f, indent=4, ensure_ascii=False)


def create_path_from_name(name):
    name = re.sub(r'[^\w\s-]', '', name, flags=re.UNICODE)
    name = name.replace(" ", "-").replace("_", "-")
    name = ''.join([char.lower() if 'A' <= char <= 'Z' else char for char in name])
    return name
    
def add_link(file_path, name, value, source):
    path = create_path_from_name(name)
    data = read_json_file(file_path)
    
    if source not in data:
        data[source] = {}
    data[source][path] = value

    write_json_file(file_path, data)
    return path

def get_link(file_path, path, source, key=None):
    data = read_json_file(file_path)
    if source in data and path in data[source]:
        if key:
            return data[source][path].get(key)
        return data[source][path]
    return None

# Functions specific to manga linksض
def add_link_manga(name, url, source):
    return add_link(json_file_manga, name, url, source)

def get_link_manga(path, source):
    return get_link(json_file_manga, path, source)


# Functions specific to chapter links
def add_chapter_link(manga_name, chapter_number, chapter_url, source):
    path = create_path_from_name(manga_name)
    data = read_json_file(chapter_link_file)
    
    if source not in data:
        data[source] = {}
    if path not in data[source]:
        data[source][path] = {}
    
    data[source][path][chapter_number] = chapter_url
    write_json_file(chapter_link_file, data)
    return chapter_number
    
def get_chapter_link(path, chapter_number, source):
    chapter_url = get_link(chapter_link_file, path, source, chapter_number)
    if chapter_url:
        return chapter_url
    return get_latest_chapters(path, chapter_number, source)

# Functions specific to latest chapters

def add_latest_chapters(manga_name, chapter_number, chapter_url, source):
    path = create_path_from_name(manga_name)
    data = read_json_file(latest_chapters_file)
    
    if source not in data:
        data[source] = {}
    if path not in data[source]:
        data[source][path] = {}
    
    data[source][path][chapter_number] = chapter_url
    write_json_file(latest_chapters_file, data)
    return chapter_number
    
def get_latest_chapters(path, chapter_number, source):
    return get_link(latest_chapters_file, path, source, chapter_number)


def load_chapter(url, source):
    """Load data from a JSON file if it exists."""
    if os.path.exists(chapter_data):
        with open(chapter_data , 'r', encoding='utf-8') as file:
            data = json.load(file)
            if source in data and url in data[source]:
                return data[source][url]
    return {}

def save_chapter(data, url, source):
    if data["next_chapter_link"] is not None:
        """Save data to a JSON file."""
        # Load existing data if file exists
        existing_data = read_json_file(chapter_data)
        
        # Create or update the source data
        if source not in existing_data:
            existing_data[source] = {}
        existing_data[source][url] = data
        
        # Write the updated data to the JSON file
        write_json_file(chapter_data, existing_data)

hikoky/blueprints/chapter/routes.py
from flask import Blueprint, render_template, flash, redirect, url_for
from config import source_handlers
from hikoky.blueprints.utils import get_handler_and_check_errors, chapter_handler

chapter = Blueprint('chapter', __name__)

app_name = "Hikoky"  

@chapter.route('/<source>/<manga_path>/<chapter_num>')
@chapter.route('/<source>/<manga_path>/<chapter_num>/')
def display_manga(source, manga_path, chapter_num):
    handler, error_response = get_handler_and_check_errors(source)
    if error_response:
        return error_response
    
    return chapter_handler(handler, manga_path, chapter_num, source, app_name)

hikoky/blueprints/main/routes.py
from flask import Blueprint, render_template, request, flash, jsonify, url_for, redirect
from config import source_handlers
from hikoky.blueprints.utils import get_handler_and_check_errors, home_handler

main = Blueprint('main', __name__)

app_name = "Hikoky"  

@main.route('/')
def sources():
    return render_template('sources.html', app_name=app_name)

@main.route('/<source>')
@main.route('/<source>/')
def home(source):
    handler, error_response = get_handler_and_check_errors(source)
    if error_response:
        return error_response
        
    return home_handler(request.args.get('next_page_url'), handler, app_name, source)

@main.route('/search/<source>/')
@main.route('/search/<source>')
def search(source):
    return "<h1>قريبا</h1>"

hikoky/blueprints/manga/routes.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from config import source_handlers
from hikoky.blueprints.utils import get_handler_and_check_errors
from hikoky.blueprints.utils import manga_handler

manga = Blueprint('manga', __name__)

app_name = "Hikoky"  

@manga.route('/<source>/<manga_path>')
@manga.route('/<source>/<manga_path>/')
def manga_home(source, manga_path):
    handler, error_response = get_handler_and_check_errors(source)
    if error_response:
        return error_response
        
    return manga_handler(handler, source, manga_path, app_name)

@manga.route('/load_more')
def load_more():
    source = request.args.get('source')
    handler, error_response = get_handler_and_check_errors(source)
    if error_response:
        return error_response
    
    url = request.args.get('nextPageUrl')
    return manga_handler(handler, source, None, None, more=True, url=url)

hikoky/blueprints/utils.py
# hikoky/blueprints/utils.py
from flask import Blueprint, render_template, request, flash, jsonify, url_for, redirect
from config import source_handlers
from hikoky.scrapers.PyProbe.PyParse import pyparse
from hikoky.scrapers.urls import get_link_manga, get_chapter_link, load_chapter, save_chapter

def get_handler_and_check_errors(source):
    handler = source_handlers.get(source)
    if not handler:
        flash("المصدر غير متوفر", 'danger')
        return None, redirect(url_for('main.sources'))
    return handler, None
    
def home_handler(url, handler, app_name, source):
    url = request.args.get('next_page_url') or handler["url"]
    
    result = pyparse(url) 
    if isinstance(result, dict) and 'error' in result:
        flash(result['error'], 'danger')
        return render_template('home.html', app_name=app_name, current_source=source)
        
    results, next_page_url = handler["home_page"](result)
    
    if request.args.get('next_page_url'):
        return jsonify(results=results, next_page_url=next_page_url)

    return render_template('home.html', results=results, next_page_url=next_page_url, app_name=app_name, current_source=source)
    
def manga_handler(handler, source, manga_path, app_name, more=False, url=None):
    if more is False:
        url = get_link_manga(manga_path, source=source) 

    result = pyparse(url) 
    if isinstance(result, dict) and 'error' in result:
        flash(result['error'], 'danger')
        return render_template('manga.html', info_manga=None, app_name=app_name, current_source=source)
    
    info_manga, chapters, next_page_link = handler["manga_page"](result)
    if more:
        return jsonify(chapters=chapters, next_page_link=next_page_link)
    else:
        return render_template('manga.html', info_manga=info_manga, chapters=chapters, next_page_link=next_page_link, app_name=app_name, current_source=source)


def chapter_handler(handler, manga_path, chapter_num, source, app_name):
    url = get_chapter_link(manga_path, chapter_num, source=source)
    
    result = load_chapter(url, source=source)
    if result:
        return render_template('chapter.html', manga_info=result, app_name=app_name, current_source=source)
    else:
        result = pyparse(url) 
        if isinstance(result, dict) and 'error' in result:
            flash(result['error'], 'danger')
            return render_template('chapter.html')
        result = handler["chapter_page"](result, url)
            
    save_chapter(result, url, source=source)
    return render_template('chapter.html', manga_info=result, app_name=app_name, current_source=source)

hikoky/templates/chapter.html
<!-- templates/chapter.html -->
{% extends "layout.html" %}
{% block title %}{{ manga_info.title }}{% endblock %}

{% block extra_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/chapter.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
{% endblock %}

{% block content %}
    <div id="Button">
        <div id="FullScreen" onclick="toggleFullScreen()">
            <i class="fa-solid fa-expand fa-2xs" style="color: #404040;"></i>
        </div>
    </div>
    
    <div class="container">
        <div class="title">
            <h1>{{ manga_info.title }}</h1>
        </div>

        <div class="chapter" id="readerarea">
            {% for image_url in manga_info.image_urls %}
                <div class="page-break">
                    <img id="image-{{ loop.index }}" data-src="{{ image_url }}" alt="{{ manga_info.name }} {{ loop.index }}/{{ loop.length }}" class="chapter-image lazy" style="display:none;">
                </div>
            {% endfor %}
        </div>

        <div class="navigation no-select" id="bottom-navigation">
            {% if manga_info.prev_chapter_link %}
                <a href="{{ request.path | replace(request.path.split('/')[-1], manga_info.prev_chapter_link) }}" class="Previous">السابق</a>
            {% else %}
                <a class="Previous hidden">السابق</a>
            {% endif %}
        
            {% if manga_info.next_chapter_link %}
                <a href="{{ request.path | replace(request.path.split('/')[-1], manga_info.next_chapter_link) }}" class="Next">التالي</a>
            {% else %}
                <a class="Next hidden">التالي</a>
            {% endif %}
        </div>
    </div>
{% endblock %}
{% block extra_js %}
    <script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@17.3.0/dist/lazyload.min.js"></script>
    <script src="{{ url_for('static', filename='js/chapter.js') }}"></script>
{% endblock %}

hikoky/templates/home.html
<!-- templates/home.html -->
{% extends "layout.html" %}
{% block title %}قائمة المانجا{% endblock %}
{% block extra_css %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/home.css') }}">
{% endblock %}

{% block content %}
    <div class="heading">
        <h1 id="heading-title" class="no-select">أحدث الإضافات</h1>
    </div>
    <div class="manga-list">
        {% for result in results %}
            <div class="box">
                <div class="manga">
                    <div id="manga-item-{{ result.id }}" class="item-thumb c-image-hover" data-post-id="{{ result.id }}">
                        <a href="{{ request.path }}/{{ result.manga_link }}" title="{{ result.manga_name }}">
                            {% if result.translation_team %}
                                <span class="manga-title-badges">{{ result.translation_team }}</span>
                            {% endif %}
                            <img src="{{ result.manga_cover }}" alt="{{ result.manga_name }}">
                        </a>
                    </div>
                    <div class="post-title">
                        <h3 class="h5">
                            <a href="{{ request.path }}/{{ result.manga_link }}">{{ result.manga_name }}</a>
                        </h3>
                    </div>
                    <div class="list-chapter">
                        <div class="chapter-item has-thumb">
                            <span class="chapter font-meta">
                                {% if result.chapters_info.latest_chapter_number %}
                                    <a href="{{ request.path }}/{{ result.manga_link }}/{{ result.chapters_info.latest_chapter_url }}" class="btn-link">{{ result.chapters_info.latest_chapter_number }}</a>
                                {% endif %}
                            </span>
                        </div>
                        <div class="chapter-item has-thumb">
                            <span class="chapter font-meta">
                                {% if result.chapters_info.penultimate_chapter_number %}
                                    <a href="{{ request.path }}/{{ result.manga_link }}/{{ result.chapters_info.penultimate_chapter_url }}" class="btn-link">{{ result.chapters_info.penultimate_chapter_number }}</a>
                                {% endif %}
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% if next_page_url %}
    <div class="more">
        <div class="loading-dots">
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
        </div>
        <button id="load-more" data-url="{{ next_page_url }}" class="btn btn-primary no-select">
            المزيد
        </button>
    </div>
    {% endif %}
{% endblock %}

{% block extra_js %}
    <script src="{{ url_for('static', filename='js/jquery_home.js') }}"></script>
{% endblock %}

hikoky/templates/layout.html
<!DOCTYPE html>
<html lang="ar">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ app_name }} | {% block title %}{% endblock %}</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@6.5.2/css/all.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}">
    {% block extra_css %}
    
    {% endblock %}
</head>
<body>
    <header>
        <nav class="nav-bar">
            <div class="container-nav">
                <a class="logo" href="{{ url_for('main.sources') }}">
                    <h1 class="logo">{{ app_name }}</h1>
                </a>
                <div class="menu" id="navbarNav">
                    <ul class="navlist">
                        {% if current_source %}
                            <li class="navitem">
                                <a class="navlink" href="{{ url_for('main.home', source=current_source) }}">
                                    <i class="fas fa-home"></i>
                                </a>
                            </li>
                            <li class="navitem"> 
                                <a class="navlink" href="{{ url_for('main.search', source=current_source) }}">
                                    <i class="fas fa-search"></i>
                                </a>
                            </li>
                        {% endif %}
                        <li class="navitem">
                            <button id="theme-toggle" onclick="toggleTheme()">
                                <i id="theme-icon" class="fas fa-moon"></i>
                            </button>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main>
        <div class="container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    <div class="alert-container">
                        {% for category, message in messages %}
                            <div class="alert alert-{{ category }}">
                                {% if category == 'danger' %}
                                    <i class="fas fa-exclamation-circle"></i>
                                {% elif category == 'success' %}
                                    <i class="fas fa-check-circle"></i>
                                {% elif category == 'info' %}
                                    <i class="fas fa-info-circle"></i>
                                {% elif category == 'warning' %}
                                    <i class="fas fa-exclamation-triangle"></i>
                                {% endif %}
                                {{ message }}
                            </div>
                        {% endfor %}
                    </div>
                {% endif %}
            {% endwith %}

            {% block content %}
            
            {% endblock %}
        </div>
    </main>
    {% block extra_js %}
    {% endblock %}
    <footer class="footer">
        <div class="container-footer">
            <div class="social-links">
                <a href="https://twitter.com/xMohnad13 " class="social-link" target="_blank">
                    <i class="fab fa-twitter"></i> 
                    <i class="fa-brands fa-x-twitter"></i>تويتر
                </a>
                <a href="https://t.me/xMohnad" class="social-link" target="_blank">
                    <i class="fab fa-telegram-plane"></i> تليجرام
                </a>
            </div>
        </div>
    </footer>
    <script>
        function toggleTheme() {
            const body = document.body;
            const themeIcon = document.getElementById('theme-icon');
            body.classList.toggle('light-mode');
    
            if (body.classList.contains('light-mode')) {
                localStorage.setItem('theme', 'light');
                themeIcon.classList.remove('fa-moon');
                themeIcon.classList.add('fa-sun');
            } else {
                localStorage.removeItem('theme');
                themeIcon.classList.remove('fa-sun');
                themeIcon.classList.add('fa-moon');
            }
        }
    
        document.addEventListener('DOMContentLoaded', () => {
            const themeIcon = document.getElementById('theme-icon');
            if (localStorage.getItem('theme') === 'light') {
                document.body.classList.add('light-mode');
                themeIcon.classList.remove('fa-moon');
                themeIcon.classList.add('fa-sun');
            } else {
                themeIcon.classList.remove('fa-sun');
                themeIcon.classList.add('fa-moon');
            }
        });

        document.addEventListener('DOMContentLoaded', () => {
            const year = new Date().getFullYear();
            document.querySelector('.footer-bottom p').innerHTML = `${year} {{ app_name }}.`;
        });
    </script>
</body>
</html>

hikoky/templates/manga.html
<!-- templates/manga.html -->
{% extends "layout.html" %}

    {% if info_manga %}
{% block title %}{{ info_manga.manganame }}{% endblock %}
    {% endif %}

{% block extra_css %}
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/manga.css') }}">
{% endblock %}

{% block content %}
    {% if info_manga %}
    <div class="cover-and-info">
        <div class="cover">
            <img src="{{ info_manga.cover_manga }}" alt="{{ info_manga.manganame }}" class="img-fluid rounded shadow-sm">
        </div>
        <div class="info">
            <h1>{{ info_manga.manganame }}</h1>
            <div class="mb-3">
                {% for genre in info_manga.genres %}
                    <span class="badge ar badge-primary">{{ genre }}</span>
                {% endfor %}
            </div>
            <p class="ar">{{ info_manga.review_text }}</p>
        </div>
    </div>
    {% endif %}
    <br />        
    {% if info_manga.chapter_number %}
        <h2>({{ info_manga.chapter_number }}) فصول المانجا</h2>
    {% else %}
        <h2>فصول المانجا</h2>
    {% endif %}
    <div class="chapters ar">
        {% if info_manga %}
        <ul class="list">
            {% for chapter in chapters %}
                <li class="chapter-item">
                    <a href="{{ request.path }}/{{ chapter.number }}">
                        الفصل {{ chapter.number }}
                        <span class="date">{{ chapter.date }}</span>
                    </a>
                </li>
        {% endfor %}
        </ul>
        {% endif %}
        <div class="loading-dots">
            <div class="dot"></div>
            <div class="dot"></div>
            <div class="dot"></div>
        </div>
        {% if next_page_link %}
            <div class="more" data-url="{{ next_page_link }}"></div>
        {% endif %}
    </div>
{% endblock %}

{% block extra_js %}
    <script src="{{ url_for('static', filename='js/jquery_manga.js') }}"></script>
{% endblock %}

hikoky/templates/sources.html
{% extends "layout.html" %}
{% block title %}المصادر{% endblock %}

{% block extra_css %}

{% endblock %}
{% block content %}
    <div class="Sources">
        <a href="/teamx">
            <img src="https://www.teamxnovel.com/images/TeamX.png" alt="Team-X Logo">
            Team-X
        </a>
        <a href="/3asq">
            <img src="https://static.gameloop.com/img/34ea0309b0bbf020fa3f1be037b3baf7.png?imageMogr2/thumbnail/172.8x172.8/format/webp" alt="3asq Logo">
            3asq
        </a>
    </div>
{% endblock %}